# 
# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate cv
# $ python -m ipykernel install --user --name automl-workshop
# 
name: automl-workshop
channels:
- defaults
- conda-forge
dependencies:
- python==3.6.8
- pip:
  - azureml-sdk[notebooks,automl,explain,contrib]==1.0.76
  - azureml-dataprep
